services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app/app
      - ./backend/.env:/app/.env
    expose:
      - "8000"
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=/api
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: